/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SearchInfo struct {
	Type_    string `json:"type,omitempty"`
	Value    string `json:"value,omitempty"`
	Alias    string `json:"alias,omitempty"`
	Id       int64  `json:"id,omitempty"`
	TeseraId int64  `json:"teseraId,omitempty"`
	Title    string `json:"title,omitempty"`
	Title2   string `json:"title2,omitempty"`
	PhotoUrl string `json:"photoUrl,omitempty"`
}
