/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ReportPlaceInfo struct {
	Id              int64     `json:"id,omitempty"`
	Title           string    `json:"title,omitempty"`
	Type_           string    `json:"type,omitempty"`
	CreationDateUtc time.Time `json:"creationDateUtc,omitempty"`
}
