/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddPostModel struct {
	// Post title
	Title string `json:"title,omitempty"`
	// Post alias
	Alias string `json:"alias,omitempty"`
	// Is draft
	IsDraft bool `json:"isDraft,omitempty"`
	// Post blocks
	Blocks []PostBlockInfo `json:"blocks,omitempty"`
}
