/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReportAdditionInfoResponse struct {
	Addition *GameInfoShort `json:"addition,omitempty"`
	Config   *ReportConfig  `json:"config,omitempty"`
}
