/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AuthInfo struct {
	Authenticated       bool         `json:"authenticated,omitempty"`
	TeseraId            int64        `json:"teseraId,omitempty"`
	Login               string       `json:"login,omitempty"`
	Name                string       `json:"name,omitempty"`
	AvatarUrl           string       `json:"avatarUrl,omitempty"`
	Country             *CountryInfo `json:"country,omitempty"`
	City                *CityInfo    `json:"city,omitempty"`
	UnreadMessages      int64        `json:"unreadMessages,omitempty"`
	RightGroup          string       `json:"rightGroup,omitempty"`
	ModificationDateUtc time.Time    `json:"modificationDateUtc,omitempty"`
}
