/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LinkInfo struct {
	TeseraId   int64             `json:"teseraId,omitempty"`
	ObjectType string            `json:"objectType,omitempty"`
	Title      string            `json:"title,omitempty"`
	PhotoUrl   string            `json:"photoUrl,omitempty"`
	Author     *UserInfoShort    `json:"author,omitempty"`
	Game       *GameInfoShort    `json:"game,omitempty"`
	Article    *ArticleInfoShort `json:"article,omitempty"`
	News       *NewsInfoShort    `json:"news,omitempty"`
	Thought    *ThoughtInfoShort `json:"thought,omitempty"`
}
