/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type PublicationInfoRating struct {
	CreationDateUtc time.Time      `json:"creationDateUtc,omitempty"`
	Rating          float64        `json:"rating,omitempty"`
	Comment         string         `json:"comment,omitempty"`
	Author          *UserInfoShort `json:"author,omitempty"`
}
