/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AddGameToCollectionModel struct {
	// Comment
	Comment string `json:"comment,omitempty"`
	// Game alias
	Alias string `json:"alias,omitempty"`
	// Game add or firstplay date
	EventDate time.Time `json:"eventDate,omitempty"`
}
