/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FeedSubscribeModel struct {
	// Subscribe object
	ObjectType string `json:"objectType,omitempty"`
	// Subscribe object id
	Alias string `json:"alias,omitempty"`
}
