/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type UserSubscribeItemInfo struct {
	Alias           string    `json:"alias,omitempty"`
	ObjectType      string    `json:"objectType,omitempty"`
	CreationDateUtc time.Time `json:"creationDateUtc,omitempty"`
}
