/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReportConfigPoints struct {
	RecordId int64  `json:"recordId,omitempty"`
	Name     string `json:"name,omitempty"`
}
