/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UpdateMapLocationModel struct {
	// Address line
	Address string `json:"address,omitempty"`
	// Coord
	CoordFirst float64 `json:"coordFirst,omitempty"`
	// Coord
	CoordSecond float64 `json:"coordSecond,omitempty"`
	TailFirst   int64   `json:"tailFirst,omitempty"`
	TailSecond  int64   `json:"tailSecond,omitempty"`
	ViewType    int64   `json:"viewType,omitempty"`
	CityName    string  `json:"cityName,omitempty"`
	CountryName string  `json:"countryName,omitempty"`
}
