/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReportPlayerInfoResponse struct {
	Player *ReportPlayerInfo `json:"player,omitempty"`
}
