/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BlockData struct {
	File       *FileToObjectInfo  `json:"file,omitempty"`
	Game       *GameInfoShort     `json:"game,omitempty"`
	Files      []FileToObjectInfo `json:"files,omitempty"`
	Person     *PersonInfo        `json:"person,omitempty"`
	PersonRole *PersonRoleInfo    `json:"personRole,omitempty"`
	Text       string             `json:"text,omitempty"`
	List       *ListBlock         `json:"list,omitempty"`
}
