/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddAdvertModel struct {
	// Price
	Price float64 `json:"price,omitempty"`
	// Content
	Content string `json:"content,omitempty"`
	// Game alias
	GameAlias string `json:"gameAlias,omitempty"`
	// Board condition
	Condition string `json:"condition,omitempty"`
	// City id
	CityId int64 `json:"cityId,omitempty"`
}
