/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PersonRoleInfo struct {
	Id    int64  `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
	Alias string `json:"alias,omitempty"`
}
