/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CountryInfo struct {
	Type_    string `json:"type,omitempty"`
	Value    string `json:"value,omitempty"`
	Alias    string `json:"alias,omitempty"`
	TeseraId int64  `json:"teseraId,omitempty"`
	Name     string `json:"name,omitempty"`
	Name2    string `json:"name2,omitempty"`
}
