/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjectRights struct {
	Create string `json:"create,omitempty"`
	Change string `json:"change,omitempty"`
	Delete string `json:"delete,omitempty"`
}
