/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjectInfo struct {
	Id            int64  `json:"id,omitempty"`
	TeseraId      int64  `json:"teseraId,omitempty"`
	CommentsTotal int64  `json:"commentsTotal,omitempty"`
	PictureUrl    string `json:"pictureUrl,omitempty"`
	Alias         string `json:"alias,omitempty"`
	Title         string `json:"title,omitempty"`
	ObjectType    string `json:"objectType,omitempty"`
}
