/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type TradeCollectionGameInfo struct {
	Status          string         `json:"status,omitempty"`
	CreationDateUtc time.Time      `json:"creationDateUtc,omitempty"`
	Comment         string         `json:"comment,omitempty"`
	Price           float64        `json:"price,omitempty"`
	IsNew           bool           `json:"isNew,omitempty"`
	IsOld           bool           `json:"isOld,omitempty"`
	Game            *GameInfoShort `json:"game,omitempty"`
}
