/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ArticleInfoShort struct {
	TeseraId            int64     `json:"teseraId,omitempty"`
	Alias               string    `json:"alias,omitempty"`
	Title               string    `json:"title,omitempty"`
	Title2              string    `json:"title2,omitempty"`
	TitleOther          string    `json:"titleOther,omitempty"`
	ContentShort        string    `json:"contentShort,omitempty"`
	CreationDateUtc     time.Time `json:"creationDateUtc,omitempty"`
	ModificationDateUtc time.Time `json:"modificationDateUtc,omitempty"`
	PublicationDateUtc  time.Time `json:"publicationDateUtc,omitempty"`
	PhotoUrl            string    `json:"photoUrl,omitempty"`
	Rating              float64   `json:"rating,omitempty"`
	CommentsTotal       int64     `json:"commentsTotal,omitempty"`
	NumVotes            int64     `json:"numVotes,omitempty"`
}
