/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CollectionGameCountResponse struct {
	TotalCount    int64 `json:"totalCount,omitempty"`
	SelfGameCount int64 `json:"selfGameCount,omitempty"`
	AdditionCount int64 `json:"additionCount,omitempty"`
}
