/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MapLocationInfo struct {
	Id          int64   `json:"id,omitempty"`
	Address     string  `json:"address,omitempty"`
	CoordFirst  float64 `json:"coordFirst,omitempty"`
	CoordSecond float64 `json:"coordSecond,omitempty"`
	TailFirst   int64   `json:"tailFirst,omitempty"`
	TailSecond  int64   `json:"tailSecond,omitempty"`
	ViewType    int64   `json:"viewType,omitempty"`
}
