/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UpdateUserSettingsModel struct {
	// User name
	FullName string `json:"fullName,omitempty"`
	// Password
	Password string `json:"password,omitempty"`
	// Gender
	Gender string `json:"gender,omitempty"`
	// Avatar url
	AvatarUrl string `json:"avatarUrl,omitempty"`
	// Profile description
	Comment string `json:"comment,omitempty"`
	// User country id
	CountryId int64 `json:"countryId,omitempty"`
	// User city id
	CityId    int64 `json:"cityId,omitempty"`
	IamPlayer bool  `json:"iamPlayer,omitempty"`
	IamClub   bool  `json:"iamClub,omitempty"`
	IamShop   bool  `json:"iamShop,omitempty"`
	IamEvent  bool  `json:"iamEvent,omitempty"`
	// Subscribe to messages
	SubscribeMessages bool `json:"subscribeMessages,omitempty"`
	// Subscribe to feed
	SubscribeFeed bool `json:"subscribeFeed,omitempty"`
	// User bgg login
	BggLogin string `json:"bggLogin,omitempty"`
	// Auto import game reports from bgg
	AutoImport bool `json:"autoImport,omitempty"`
	// Imported reports access type
	ImportAccessType string `json:"importAccessType,omitempty"`
}
