/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PostRatingModel struct {
	// User's comment
	Comment string `json:"comment,omitempty"`
	// User's rating
	Rating int64 `json:"rating,omitempty"`
}
