/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateListElementModel struct {
	// Element description
	Description string `json:"description,omitempty"`
	ObjectId    int64  `json:"objectId,omitempty"`
}
