/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReportUserInfo struct {
	ReadyCount int64 `json:"readyCount,omitempty"`
	DraftCount int64 `json:"draftCount,omitempty"`
	Total      int64 `json:"total,omitempty"`
}
