/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReportRatingResponse struct {
	Likes   int64 `json:"likes,omitempty"`
	IsLiked bool  `json:"isLiked,omitempty"`
}
