/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReportConfig struct {
	Side             []ReportConfigSide `json:"side,omitempty"`
	ResultType       string             `json:"resultType,omitempty"`
	PointsCategories []ReportPointsInfo `json:"pointsCategories,omitempty"`
}
