/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MessagesByUserResponse struct {
	Author    *UserInfoShort               `json:"author,omitempty"`
	Companion *UserInfoShort               `json:"companion,omitempty"`
	List      *PagedListOfMessageInfoShort `json:"list,omitempty"`
}
