/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BggReportsImportResponse struct {
	Reports []ReportInfo `json:"reports,omitempty"`
	Status  int64        `json:"status,omitempty"`
	Message string       `json:"message,omitempty"`
}
