/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ListInfo struct {
	TeseraId            int64          `json:"teseraId,omitempty"`
	Title               string         `json:"title,omitempty"`
	Title2              string         `json:"title2,omitempty"`
	Title3              string         `json:"title3,omitempty"`
	Alias               string         `json:"alias,omitempty"`
	Description         string         `json:"description,omitempty"`
	DescriptionShort    string         `json:"descriptionShort,omitempty"`
	PhotoUrl            string         `json:"photoUrl,omitempty"`
	ModificationDateUtc time.Time      `json:"modificationDateUtc,omitempty"`
	CreationDateUtc     time.Time      `json:"creationDateUtc,omitempty"`
	RatingUser          float64        `json:"ratingUser,omitempty"`
	MainPage            bool           `json:"mainPage,omitempty"`
	AuthorId            int64          `json:"authorId,omitempty"`
	Author              *UserInfoShort `json:"author,omitempty"`
	CommentsTotal       int64          `json:"commentsTotal,omitempty"`
	ItemsTotal          int64          `json:"itemsTotal,omitempty"`
	Rights              *ObjectRights  `json:"rights,omitempty"`
}
