/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddReportPlayerModel struct {
	// Place title
	Name string `json:"name,omitempty"`
	// Referenced user Id
	ReferencedUserId int64 `json:"referencedUserId,omitempty"`
}
