/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ListBlock struct {
	Type_ string   `json:"type,omitempty"`
	Items []string `json:"items,omitempty"`
}
