/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GameInCollectionInfo struct {
	Title        string                   `json:"title,omitempty"`
	Description  string                   `json:"description,omitempty"`
	Type_        string                   `json:"type,omitempty"`
	Id           int64                    `json:"id,omitempty"`
	InCollection bool                     `json:"inCollection,omitempty"`
	Item         *CollectionGameInfoShort `json:"item,omitempty"`
}
