/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CollectionInfo struct {
	CollectionType string       `json:"collectionType,omitempty"`
	GamesTotal     int64        `json:"gamesTotal,omitempty"`
	GamesTotalAll  int64        `json:"gamesTotalAll,omitempty"`
	SelfGamesCount int64        `json:"selfGamesCount,omitempty"`
	AdditionsCount int64        `json:"additionsCount,omitempty"`
	Items          []AdvertInfo `json:"items,omitempty"`
}
