/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReportImportModel struct {
	// User login
	UserName   string `json:"userName,omitempty"`
	AccessType int64  `json:"accessType,omitempty"`
	ToggleAuto bool   `json:"toggleAuto,omitempty"`
}
