/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type FeedEventInfo struct {
	Id              int64     `json:"id,omitempty"`
	SubscribeId     int64     `json:"subscribeId,omitempty"`
	Message         string    `json:"message,omitempty"`
	EventType       string    `json:"eventType,omitempty"`
	SubscribeType   string    `json:"subscribeType,omitempty"`
	CreationDateUtc time.Time `json:"creationDateUtc,omitempty"`
}
