/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReportPrefill struct {
	PlayerGroups *ReportPlayerGroups `json:"playerGroups,omitempty"`
	Place        *ReportPlaceInfo    `json:"place,omitempty"`
	Additions    []GameInfoShort     `json:"additions,omitempty"`
	ResultType   string              `json:"resultType,omitempty"`
	AccessType   string              `json:"accessType,omitempty"`
	SidesUsed    bool                `json:"sidesUsed,omitempty"`
}
