/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NewsInfoShort struct {
	TeseraId      int64   `json:"teseraId,omitempty"`
	Title         string  `json:"title,omitempty"`
	Title2        string  `json:"title2,omitempty"`
	Alias         string  `json:"alias,omitempty"`
	ContentShort  string  `json:"contentShort,omitempty"`
	PhotoUrl      string  `json:"photoUrl,omitempty"`
	Rating        float64 `json:"rating,omitempty"`
	CommentsTotal int64   `json:"commentsTotal,omitempty"`
	NumVotes      int64   `json:"numVotes,omitempty"`
}
