/*
 * Tesera API
 *
 * API for Tesera
 *
 * API version: v1
 * Contact:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddCityModel struct {
	// Name city
	CityName string `json:"cityName,omitempty"`
	// Name country
	CountryName string `json:"countryName,omitempty"`
}
